### ISSUE TITLE
UINavigationController issue in the master view (iOS 6)

### ISSUE THREAD

**Issue by gzbanson** [mattgemmell/MGSplitViewController#69] opened 2012-07-20 12:44 UTC
In iOS 6, the master view seems can't layout correctly. When I rotate the iPad from landscape to portrait then back to landscape, the UINavigationController will screw up, the navigation bar has lost the color, the size of the navigation isn't correct and the content view of the UINavigationController has offset.

**Comment by fabianofrancesconi** [comment] 2012-07-25 09:01
Confirmed. Same problem here.

**Comment by cysp** [comment] 2012-07-25 09:38
As a data point, it appears that the bug only manifests in my applications if the MGSplitViewController is initially presented in portrait orientation.
If it is initially presented in landscape orientation, even multiple rotation events don't result in incorrect layout.

**Comment by fabianofrancesconi** [comment] 2012-07-25 09:41
I cannot confirm what @cysp claims.
Whenever and whatever I present the MGSVC (landscape or portrait) it is always rendered in a bad layout fashion.

**Comment by fabianofrancesconi** [comment] 2012-07-25 09:43
Another data point here: if you try to use the `toggleMasterView` method, you should obtain the same unwanted rendering. Can you confirm?

**Comment by cysp** [comment] 2012-07-25 09:55
I'm away from the code and - unfortunately - a compiler right now but I'll try that tomorrow.
I'll have another look to see if I missed something special that we're doing in landscape orientation too.

We're using the .showsMasterInPortrait option, but I don't have a theory for why that would "fix" landscape.

**Comment by gzbanson** [comment] 2012-07-25 13:06
It's looks like the issue is causing by the popoverview, when the master has "present" (including: [_hiddenPopoverController presentPopoverFromRect:CGRectZero inView:self.view permittedArrowDirections:UIPopoverArrowDirectionAny animated:NO];) as the popoverview, the UINavigationController's frame has been changed, but it didn't layout itself again when the device go back to landscape.

**Comment by cysp** [comment] 2012-07-26 00:58
OK, so landscape worked for me because of some poor code that configured the MGSplitViewController in the master VC's -loadView. So presenting in landscape prevented the UIPopoverController from being instantiated.

I guess I can confirm that the incorrect layout is related to the use of UIPopoverController, for as much as my additional voice on that point helps.

**Comment by fabianofrancesconi** [comment] 2012-07-26 08:03
That UIPopoverController is more a mess than a bless. Meh. If I only knew something more I would been able to investigate it.

**Comment by gzbanson** [comment] 2012-07-26 12:56
Is there anyway we could force the UINavigiationController relayout correctly at the right time? I tried "layoutSubviews", it didn't work for me

**Comment by nnhubbard** [comment] 2012-07-31 23:59
Have the same issue, really wanting to get this fixed!

**Comment by blitzvb** [comment] 2012-08-05 15:13
same here :/

**Comment by gzbanson** [comment] 2012-08-06 20:42
The issue seems be fixed by Apple in beta 4, I will keep this issue open until Apple release the GM build, thx everyone.

**Comment by fabianofrancesconi** [comment] 2012-08-07 14:22
I can confirm this too. It seems working as before in iOS 6b4

**Comment by nnhubbard** [comment] 2012-08-07 22:58
Not working like before for me. Now my entire split view is about half the height...but doing the following in my didFinishLaunchingWithOptions fixed it:

[self.tabController setSelectedIndex:1];
[self.tabController setSelectedIndex:0];

**Comment by blitzvb** [comment] 2012-08-23 14:57
the problem seems to occur only in landscape for me on the beta 4. half of the screen is black.

**Comment by tristanseifert** [comment] 2012-08-24 20:27
I can confirm the problem @nnhubbard mentioned - the split view doesn't render right in landscape on iOS6b4, although it renders fine in portrait as well as when rotating from Landscape. If you can't use @nnhubbard's workaround, the below workaround works for me (and does not seem to have any side effects besides a very unnoticable 1 pixel move):

``` obj-c
            // at some point in your code
            [_splitView setSplitPosition:splitView.splitPosition - 1];

            // a little later
            [_splitView setSplitPosition:splitView.splitPosition + 1];
```

**Comment by blitzvb** [comment] 2012-08-24 22:04
this affect the demo too. Just start it on iOS 6.0 b4 and the orientation is not taken in account anymore. Actually upon investigation those methods are not called anymore :

willRotateToInterfaceOrientation
didRotateFromInterfaceOrientation

all shouldAutorotateToInterfaceOrientation return YES so to me those methods should be called.

**Comment by akac** [comment] 2012-09-06 18:59
iOS 5 and before would start iPad apps in portrait mode and then call the rotate methods to move it to landscape. iOS 6 launches right into landscape if you build against the iOS 6 SDK.

**Comment by akac** [comment] 2012-09-06 18:59
Are there any forks of this project that have this fixed in the source itself?

**Comment by Flufflicks** [comment] 2012-09-13 08:45
I can also confirm this problem. In my project I used the following code to add the splitCon to my window:
[self.window addSubview:splitCon.view];

after i changed it to:
self.window.rootViewController = splitCon;
it works correct like in iOS5  :)

**Comment by ghost** [comment] 2012-09-13 15:08
The Sample project doesn't work anymore if you build your project on Xcode 4.5 or using deployment target as iOS 6.0. The issue is with Rotation methods it has been using, have been changed in iOS 6.0 - http://9to5mac.com/2012/06/25/apple-pushes-ios-6-0-update-to-devs/ I tried using new shouldAutoRotate and SupportedOrientations methods but it didn't make any difference. Could someone please throw some lights here. Thanks.

**Comment by ghost** [comment] 2012-09-13 15:09
Funny thing is it works on iOS6 if you build your project on lower version on Xcode(say 4.4) with deployment target set to iOS 5.0.

**Comment by cheesemaker** [comment] 2012-09-13 16:14
To update this for the 6.0 GM, you must do the following:
1. change any instances in your code of [window addSubview:splitviewController.view] to [window setRootViewController:splitviewController]
2. MGSplitViewController has a layout bug that occurs when you start in landscape mode under iOS 6 that will cause it to start with the view improperly sized. To fix, add the following after you have set it as the root view controller:
    [splitViewController setSplitPosition:splitViewController.splitPosition - 1];
    [splitViewController setSplitPosition:splitViewController.splitPosition + 1];

Then you should be back in business.  These changes are harmless on previous OS versions back to OS 4.0.  However, be aware that setRootViewController doesn't exist prior to OS 4 so if you need to support OS 3.x you will need to have branching code to check for the version and use addSubview on OS 3.x instead.

**Comment by akac** [comment] 2012-09-13 17:20
Actually I found a much better way than this for iOS 6 support. The setting of the split is unneeded. I plan to upload my fork soon. It's somewhat heavily modified but works very well. One major change is I no longer use popovers for the master. 

## 

Alex Kac CEO/Founder
Transcribed by Siri

**Comment by gzbanson** [comment] 2012-09-13 17:25
Thanks all your help and reply guys

**Comment by jgale** [comment] 2012-09-14 00:04
Is anyone else finding that @cheesemaker's fixes are not enough for them on iOS 6 GM? The split view still takes up only half the vertical space of the screen when launched in Landscape for me. @akac, I don't see any commits on your fork?

**Comment by akac** [comment] 2012-09-14 00:05
Sorry, been busy. Still planning on putting it up shortly.

On Sep 13, 2012, at 7:04 PM, Jeremy Gale notifications@github.com wrote:

> Is anyone else finding that @cheesemaker's fixes are not enough for them on iOS 6 GM? The split view still takes up only half the vertical space of the screen when launched in Landscape for me. @akac, I don't see any commits on your fork?
> 
> —
> Reply to this email directly or view it on GitHub.

Alex Kac - President and Founder
Web Information Solutions, Inc. 

"If at first you don't succeed, skydiving is not for you."
-- Francis Roberts

**Comment by jgale** [comment] 2012-09-14 00:05
Awesome, looking forward to it. Thanks! :)

**Comment by jgale** [comment] 2012-09-14 00:14
I realized my problem - I needed to do the adjustment of the splitPosition after didFinishLaunchingWithOptions. I did it in the viewDidLoad of my master view controller.

**Comment by ghost** [comment] 2012-09-14 09:38
@cheesemaker I have made splitviewControlle as root view controller and everything fixed it. I don't see issue when App starts in Landscap mode. It adjusts views automatically. I have built project in XCode 4.5 deployment target to iOS 6.0.

**Comment by aporat** [comment] 2012-09-15 16:06
I resolved the issue by adding
`
[self.splitViewController willAnimateRotationToInterfaceOrientation:UIInterfaceOrientationLandscapeRight
                                                               duration:0];` 

after the `makeKeyAndVisible` class in the app delegate.

On another note, did anyone notice a strange touch behavior with `UIInterfaceOrientationLandscapeLeft`? the master view controller is not responding to touch events correctly. seems to happen with the stock `UISplitViewController` as well.

**Comment by jgale** [comment] 2012-09-17 21:18
@aporat I am noticing that now too. No touches seem to be registered in the top-right corner of the screen when used in Landscape mode on iOS 6 (UIInterfaceOrientationLandscapeLeft or UIInterfaceOrientationLandscapeRight). I haven't figured out why yet. Let me know if you discover anything. Very interesting if it also happens with stock UISplitViewController.

**Comment by aporat** [comment] 2012-09-17 21:24
I'm glad it's not just my app. I couldn't solve this issue, so I disabled the `UIInterfaceOrientationLandscapeLeft` orientation. Happens on an actual ipad 2, so it's not just the simulator broken.

It does happen with the stock `UISplitViewController`, which let me believe it's a bug in the ios 6 gm /  xcode 4.5. I'll try to replicate it on a new project and submit a bug report to apple.

**Comment by jgale** [comment] 2012-09-17 22:27
I am actually seeing it on _any_ app that I run in Landscape on iOS 6 iPad simulator, non-retina only. Even brand new Xcode New Project templates, not even using UISplitViewController. This makes me think it's just an Xcode bug, but it scares me that you are seeing it on an actual device. 

Note: Retina simulator works fine. I am seeing this when both in landscape left or landscape right.

I will have to try on a real device and see if it still happens for me. Unfortunately I don't have any iPad 2s around.

**Comment by Nygashi** [comment] 2012-09-19 09:48
Just add [self layoutSubviews]; to the viewDidAppear instead of the viewWillAppear in MGSplitViewController. Problem solved.

**Comment by ArtSabintsev** [comment] 2012-09-20 16:14
@Nygashi is correct. You have to add [self layoutSubviews] in viewDidAppear **and** change the method in which you present your MGSplitViewController instance. Instead of adding tot he window's subview, just set the window's rootVC.

**Comment by ArtSabintsev** [comment] 2012-09-20 16:47
Forked the code and added the 2 changes here: https://github.com/ArtSabintsev/MGSplitViewController

I tested it on an iOS 6 iPad, and on iOS 5, 5.1 and 6 iPad simulators. Works fine.

**Comment by ygbr** [comment] 2012-09-21 16:38
@ArtSabintsev have you submitted a pull request?

**Comment by ArtSabintsev** [comment] 2012-09-21 16:39
Yes. I submitted it a few minutes after I uploaded the fork: https://github.com/mattgemmell/MGSplitViewController/pull/73

**Comment by jgale** [comment] 2012-09-25 17:24
Moving [self layoutSubviews]; to viewDidAppear helped with this, but the UIMapView I had in my DetailViewController was not properly sized. I had to go back to the previous approach.

**Comment by jgale** [comment] 2012-09-25 17:26
Just a note to others, one side effect of using this workaround:

```
[splitViewController setSplitPosition:splitViewController.splitPosition - 1];
[splitViewController setSplitPosition:splitViewController.splitPosition + 1];
```

was that when I launched the app in landscape on the iOS 5.0 iPad simulator, 2 of the tabs from the UITabBarController in my Master VC were missing. Rotating would fix them. iOS 5.1 and 6.0 simulators did not have this problem, so I only conditionally enabled this workaround on iOS 5.1 or higher.

**Comment by ArtSabintsev** [comment] 2012-10-02 14:37
@jgale The fix I posted doesn't use that setSplitPosition code.

**Comment by jgale** [comment] 2012-10-02 14:40
@akac Yes, I know. Moving [self layoutSubviews]; to viewDidAppear does not work for me, it caused the layout of the Detail pane to be incorrect. (MKMapView is not sized correctly). I had to use the previous workaround with setSplitPosition. Just wanted people to know in case that fix doesn't work for them either.

**Comment by ArtSabintsev** [comment] 2012-10-02 14:41
Ah, understood. Thanks for clearing that up.

**Comment by sam899** [comment] 2012-10-08 20:24
The easiest way I've found that works is to add the following to MGSplitViewController.m at the end of -(void)setup

self.view.autoresizesSubviews = NO;

It seems to work perfectly and doesn't cause the views to jump into place when they load. Can anyone confirm this with their setup?

It works with iOS 5.1 and iOS 6 (haven't tested any others)

**Comment by fittoburst** [comment] 2012-10-19 06:29
@sam899  Thanks....your solution seems to work for me.  Saved me too many late nights!

**Comment by tylerjames** [comment] 2012-10-19 15:41
@sam899 Did you ever know that you're my hero?
Fix worked for me as well. Couldn't figure out why my views thought they were supposed to be ridiculous sizes.

**Comment by sam899** [comment] 2012-10-19 15:42
Glad it's working guys! I'll submit a pull request later

**Comment by fabianofrancesconi** [comment] 2012-10-19 15:43
@sam899 I want to make love to you.

**Comment by fittoburst** [comment] 2012-10-21 18:53
@elbryan .... I think that's a bit extreme!!!!!

**Comment by fabianofrancesconi** [comment] 2012-10-22 08:22
@fittoburst yeah, you're right. There's too much hatred in the world, I tried to be dramatic :p

**Comment by fittoburst** [comment] 2012-10-22 08:26
@elbryan ... Yeah you're right. Bring it on!

**Comment by cherukkayi** [comment] 2012-10-22 12:33
I think this will work,

#if __IPHONE_OS_VERSION_MAX_ALLOWED > 6000
    [window setRootViewController:splitViewController];
#else
    [window addSubview:splitViewController.view];
#endif

```
[window makeKeyAndVisible];
```

in - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions method. :)

**Comment by xiangping-developer** [comment] 2012-12-30 17:18
@aporat 's method is work for me. This issue takes me serval hours, thanks for you sharing.

**Comment by ibiren** [comment] 2013-02-19 09:39
I am facing issue while trying to push MGSlitview into a Navigation controller.

**Closed as completed** 2013-06-11 02:25 UTC
